import React from 'react';
import { motion } from 'framer-motion';
import { FileText, ExternalLink, Lightbulb, Save, BookOpen } from 'lucide-react';
import { IntelResult } from '../../lib/ai/intel';

interface IntelResultsProps {
  result: IntelResult;
  query: string;
  onSave?: () => void;
}

export const IntelResults: React.FC<IntelResultsProps> = ({ result, query, onSave }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="space-y-4"
    >
      {/* Query Header */}
      <div className="border border-slate-800 bg-slate-900/60 rounded-lg p-4">
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1">
            <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-1">Query</p>
            <p className="text-slate-200 text-sm font-medium leading-relaxed">{query}</p>
          </div>
          {onSave && (
            <button
              onClick={onSave}
              className="flex items-center gap-2 px-3 py-1.5 bg-gradient-to-r from-cyan-600 to-violet-600 hover:from-cyan-500 hover:to-violet-500 text-white rounded-lg text-xs font-mono uppercase tracking-wider transition-all shadow-lg shadow-violet-900/20"
            >
              <Save className="w-3.5 h-3.5" />
              Save Drop
            </button>
          )}
        </div>
      </div>

      {/* Executive Summary */}
      <div className="border border-slate-800 bg-gradient-to-br from-slate-900/80 to-slate-900/40 rounded-lg overflow-hidden">
        <div className="bg-slate-900/90 px-4 py-2 border-b border-slate-800 flex items-center gap-2">
          <FileText className="w-4 h-4 text-cyan-400" />
          <h3 className="font-mono text-xs uppercase tracking-widest text-slate-300">Executive Summary</h3>
          <div className="flex-1" />
          <span className="text-[9px] font-mono text-slate-600">CLASSIFIED: LEVEL 3</span>
        </div>
        <div className="p-4 space-y-3">
          {result.summary_bullets.map((bullet, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: idx * 0.1 }}
              className="flex gap-3 group"
            >
              <div className="flex-shrink-0 mt-1">
                <div className="w-6 h-6 rounded bg-gradient-to-br from-cyan-500/20 to-violet-500/20 border border-cyan-500/30 flex items-center justify-center">
                  <span className="text-xs font-mono text-cyan-400">{idx + 1}</span>
                </div>
              </div>
              <p className="text-slate-300 text-sm leading-relaxed flex-1">{bullet}</p>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Deep Dive Essay (Conditional) */}
      {result.essay && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="border border-violet-500/30 bg-slate-900/40 rounded-lg overflow-hidden relative"
        >
          <div className="absolute inset-0 bg-violet-500/5 pointer-events-none" />
          <div className="bg-slate-900/90 px-4 py-2 border-b border-violet-500/30 flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-violet-400" />
            <h3 className="font-mono text-xs uppercase tracking-widest text-violet-300">Deep Dive Essay</h3>
            <div className="flex-1" />
            <span className="text-[9px] font-mono text-violet-500">GENERATED BY GEMINI 3.0 PRO</span>
          </div>
          <div className="p-6 text-slate-300 text-sm leading-7 space-y-4 whitespace-pre-wrap font-serif">
            {result.essay}
          </div>
        </motion.div>
      )}

      {/* Source Intelligence */}
      <div className="border border-slate-800 bg-gradient-to-br from-slate-900/80 to-slate-900/40 rounded-lg overflow-hidden">
        <div className="bg-slate-900/90 px-4 py-2 border-b border-slate-800 flex items-center gap-2">
          <ExternalLink className="w-4 h-4 text-violet-400" />
          <h3 className="font-mono text-xs uppercase tracking-widest text-slate-300">Source Intelligence</h3>
          <div className="flex-1" />
          <span className="text-[9px] font-mono text-slate-600">{result.sources.length} VERIFIED</span>
        </div>
        <div className="p-4 space-y-2">
          {result.sources.map((source, idx) => (
            <motion.a
              key={idx}
              href={source.url}
              target="_blank"
              rel="noopener noreferrer"
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.3 + idx * 0.1 }}
              className="block p-3 bg-slate-950/50 border border-slate-800 rounded-lg hover:border-violet-500/50 hover:bg-slate-950/80 transition-all group"
            >
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 w-8 h-8 rounded bg-violet-500/10 border border-violet-500/20 flex items-center justify-center group-hover:bg-violet-500/20 transition-colors">
                  <ExternalLink className="w-4 h-4 text-violet-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-slate-200 group-hover:text-violet-400 transition-colors truncate">
                    {source.title}
                  </p>
                  <p className="text-xs text-slate-500 font-mono truncate mt-0.5">{source.url}</p>
                  <p className="text-xs text-slate-400 mt-2 line-clamp-2 leading-relaxed">{source.snippet}</p>
                </div>
              </div>
            </motion.a>
          ))}
        </div>
      </div>

      {/* Related Concepts */}
      <div className="border border-slate-800 bg-gradient-to-br from-slate-900/80 to-slate-900/40 rounded-lg overflow-hidden">
        <div className="bg-slate-900/90 px-4 py-2 border-b border-slate-800 flex items-center gap-2">
          <Lightbulb className="w-4 h-4 text-amber-400" />
          <h3 className="font-mono text-xs uppercase tracking-widest text-slate-300">Related Concepts</h3>
          <div className="flex-1" />
          <span className="text-[9px] font-mono text-slate-600">FOLLOW-UP VECTORS</span>
        </div>
        <div className="p-4">
          <div className="flex flex-wrap gap-2">
            {result.related_concepts.map((concept, idx) => (
              <motion.button
                key={idx}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.5 + idx * 0.1 }}
                className="px-3 py-1.5 bg-gradient-to-r from-amber-500/10 to-orange-500/10 border border-amber-500/20 hover:border-amber-500/40 rounded-full text-xs text-amber-400 hover:text-amber-300 font-mono uppercase tracking-wide transition-all hover:scale-105"
              >
                {concept}
              </motion.button>
            ))}
          </div>
        </div>
      </div>

      {/* Metadata Footer */}
      <div className="flex items-center justify-between text-[10px] font-mono text-slate-600 uppercase tracking-wider px-2">
        <span>Generated: {new Date().toLocaleTimeString()}</span>
        <span>{result.essay ? 'Gemini 3.0 Pro' : 'Gemini 2.5 Flash'}</span>
      </div>
    </motion.div>
  );
};
